### ISSUE TITLE
Server Crashes on World Load

### ISSUE THREAD

**Issue by biomasters2** [Povstalec/StargateJourney#108]
Updated the mod to latest version from version 0.6.22, server loads fine, but then after the world itself loads it crashes. Doesn't crash on single player. Latest crash report & server log provided

[crash-2024-04-22_20.44.10-server.txt](https://github.com/Povstalec/StargateJourney/files/15069996/crash-2024-04-22_20.44.10-server.txt)

[latest.log](https://github.com/Povstalec/StargateJourney/files/15069998/latest.log)

**Comment by Povstalec** [comment]
Looks like a forgotten null check, gonna try fixing that later today.

**Comment by jinks** [comment]
I am encountering the same crash on version 0.6.25. Last thing I did was use a ring teleporter inside a goa'uld temple.

The server starts up fine, but crashed, when I join the world.

**Comment by Povstalec** [comment]
Well that doesn't make any sense, because when looking at the code, the place this crash points to being the problem is literally incapable of throwing the error. The error is a UUID error, but the crash points to a String being compared to null, no UUID involved.

I wonder if I accidentally compiled an old version or something where this null check isn't, because otherwise I have no way to explain what's going on there.

**Comment by Povstalec** [comment]
Wait, actually, are you playing on regular 0.6.25 or 0.6.25 Hotfix on your server? Because regular 0.6.25 would be capable of throwing the error, since I fixed the error in the 0.6.25 Hotfix

**Comment by biomasters2** [comment]
I've loaded up the server with the latest hotfix file and I was still getting crashes. It was the same crash log as well

**Comment by Povstalec** [comment]
Can you send the new crashlog anyway?

**Comment by biomasters2** [comment]
[crash-2024-04-25_18.28.57-server.txt](https://github.com/Povstalec/StargateJourney/files/15204227/crash-2024-04-25_18.28.57-server.txt)

**Comment by Povstalec** [comment]
Alright good, a completely different thing actually crashed, so it makes sense now. Thanks, now I know exactly what to fix.

**Comment by KadonDEngle** [comment]
Getting the same error on our ATM9 server right now. I edited the .dat file of the player who triggered the crash and changed his position out of the region. This temporarily fixed the problem, however, if anyone re-loads whatever chunk is causing the issue, the server will crash.

[crash-2024-05-05_14.12.58-server.txt](https://github.com/Povstalec/StargateJourney/files/15214987/crash-2024-05-05_14.12.58-server.txt)

Any update on a fix?

**Comment by Povstalec** [comment]
I'll fix it whenever I'm free from exams.

**Comment by Povstalec** [comment]
It should hopefully be fixed in the 0.6.26 update.

In the case that more crashing occurs, just send the newest crashlog again and I'll look at what's crashing this time.

**Comment by biomasters2** [comment]
No more crashes! Though it seems like pre-existing stargates need to be re-placed, dialing from one gave an "Unknown" error and dialing to one gave a "No Stargates in Solar System" error. Is there any other workaround besides re-placing them? How would I get to say, Abydos without the stargate so I could re-place it? Stargates that had not been dialed to before the update still make a connection.

**Comment by Povstalec** [comment]
> Though it seems like pre-existing stargates need to be re-placed, dialing from one gave an "Unknown" error and dialing to one gave a "No Stargates in Solar System" error. Is there any other workaround besides re-placing them?

That is not on purpose, nor is it something that should even be possible to happen with the mod updating. Unknown error means something happened beyond what is considered "normal" for how the Stargate Network works, usually only caused by something going wrong when updating to a new mod version or, more often, interference from other mods.

Did you try /sgjourney stargateNetwork forceStellarUpdate command? If that command can't fix it, there exists nothing I can do as the mod developer to fix it either.

**Comment by KadonDEngle** [comment]
> It should hopefully be fixed in the 0.6.26 update.
> 
> In the case that more crashing occurs, just send the newest crashlog again and I'll look at what's crashing this time.

We haven't explored the mod much, so we are unsure if it's still function as it should. That being said, the crashes in specific regions have been fixed. 

Great work and I hope your exams went well!
